# to run using this cfg, the command should be:
# python train.py -task oc -c example.yaml -s [save_dir] -exp [exp_name]

criterion:
  feat_dim: 256
  model_class: OCSoftmax
  fake_weight: 1.0 # to handle the imbalance between spoof and bonafide samples
  real_weight: 9.0
data:
  augment_type: rawboost
  batch_size: 128
  # the path should have train.tsv, dev.tsv, test.tsv and train.txt, dev.txt, test.txt
  data_path: dataset_meta/ASVspoof2019 # dataset_meta should be put in the same directory as the train.py, otherwise the path should be the absolute path
  do_augment: true
  max_samples: 64000
  model_class: GeneralFAD
  num_workers: 12
  test_batch_size: 64
  test_num_workers: 4
  upsample: false
model:
  cuda: 0
  frontend: XLSR
  frontend_path:  /mount/arbeitsdaten54/projekte/deepfake/models/xlsr2_300m.pt # the path of the pretrained model, download link can be found in the README.md
  model_class: XLSRAdapter
  num_classes: 1
train:
  # for adam optimizer
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0001
  log_interval: 20
  # lr and lr scheduler
  lr: 0.0001
  lr_gamma: 0.5
  lr_step_size: 20
  max_epoch: 100
  max_steps: 10000000000
  start_steps: 0
  validate_interval: 10000000000 # it will do validation every epoch anyway, so we use a large number to disable it
  # for early stopping
  patience: 10
  min_delta: 0.001
